from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.conf.urls import include
from material.frontend import urls as frontend_urls

urlpatterns = [
	url(r'', include(frontend_urls)),
	path('login', views.autenticar, name='Autentication'),
	path('', views.inicio, name='inicio'),
	path('logout', auth_views.logout, {'next_page': '/'}, name='logout'),	
	path('usuarios', views.gestionarusuarios, name= 'gestionarusuarios'),
	path('usuarios/', views.gestionarusuarios, name= 'gestionarusuarios'),
	path('usuarios/new', views.agregarusuario, name='agregarusuario'),
	path('usuarios/consultar/<pk>', views.detalleUsuario, name='crudUsuario'),
	path('usuarios/editar/<pk>', views.modificarUsuario, name='crudUsuario'),
	path('usuarios/eliminar/<pk>', views.eliminarUsuario),
	path('programas/', views.gestionarprogramas, name='gestionarprogramas'),
	path('programas/new', views.agregarprograma, name='agregarprograma'),
	path('programas/editar/<codigo>', views.editarPrograma, name='editarprograma'),
	path('programas/eliminar/<codigo>', views.eliminarPrograma, name='eliminarprograma'),
	path('programas/ver/<codigo>', views.verPrograma, name='verprograma'),
	path('cursos', views.gestionarCursos, name='gestionarcursos'),
	path('cursos/', views.gestionarCursos, name='gestionarcursos'),
	path('cursos/new', views.agregarCurso, name='agregarCurso'),
	path('cursos/consultar/<codigo>', views.consultarCurso),
	path('cursos/editar/<codigo>', views.modificarCurso),
	path('cursos/eliminar/<codigo>', views.eliminarCurso),
	path('competencias/<codigo_curso>', views.gestionarCompetencias),
	path('competencias/new/<codigo_curso>', views.agregarCompetencia),
	path('competencia/consultar/<codigo_competencia>', views.consultarCompetencia),
	path('competencia/editar/<codigo_competencia>', views.modificarCompetencia),
	path('competencia/eliminar/<codigo_competencia>', views.eliminarCompetencia),
	path('resultados/gestionar/<codigo_competencia>', views.gestionarResultados),
	path('resultados/new/<codigo_competencia>', views.agregarResultado),
	path('resultados/consultar/<codigo_resultado>', views.consultarResultado),
	path('resultados/editar/<codigo_resultado>', views.modificarResultado),
	path('resultados/eliminar/<codigo_resultado>', views.eliminarResultado),
	path('indicadores/gestionar/<codigo_resultado>', views.gestionarIndicadores),
	path('indicadores/new/<codigo_resultado>', views.agregarIndicador),
	path('indicadores/consultar/<codigo_indicador>', views.consultarIndicador),
	path('indicadores/editar/<codigo_indicador>', views.modificarIndicador),	
	path('indicadores/eliminar/<codigo_indicador>', views.eliminarIndicador),
	path('actividadesF/gestionar/<codigo_resultado>', views.gestionarActividadesF),
	path('actividadesF/new/<codigo_resultado>', views.agregarActividadesF),
	path('actividadesF/consultar/<codigo_actividad>', views.consultarActividadF),
	path('actividadesF/editar/<codigo_actividad>', views.modificarActividadF),	
	path('actividadesF/eliminar/<codigo_actividad>', views.eliminarActividadF),
	path('prerequisitos/<codigo_curso>', views.gestionarPreRequisitos),
	path('prerequisitos/new/<codigo_curso>', views.agregarPreRequisitos),
	path('prerequisitos/eliminar/<codigo_preRequisito>', views.eliminarPreRequisitos),
	path('getCursos/<codigo_curso>', views.getCursos),
	path('actividadesEva/gestionar/<codigo_indicador>', views.gestionarActividadesEva),
	path('actividadesEva/new/<codigo_indicador>', views.agregarActividadesEva),
	path('actividadesEva/consultar/<codigo_actividadE>', views.consultarActividadesEva),
	path('actividadesEva/editar/<codigo_actividadE>', views.modificarActividadesEva),
	path('actividadesEva/eliminar/<codigo_actividadE>', views.eliminarActividadesEva),
	path('descargarpdfcurso/<codigo_curso>', views.descargarpdfcurso),
]