# Generated by Django 2.0.4 on 2018-06-16 22:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('creditos', models.IntegerField()),
                ('horas_clase_magistral', models.IntegerField()),
                ('horas_estudio_independiente', models.IntegerField()),
                ('tipo_curso', models.CharField(choices=[('Asignatura basica', 'Asignatura basica'), ('Asignatura profesional', 'Asignatura profesional'), ('Asignatura electiva complementaria', 'Asignatura electiva complementaria'), ('Asignatura electiva profesional', 'Asignatura electiva profesional')], max_length=50)),
                ('validable', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('habilitable', models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2)),
                ('semestre', models.IntegerField()),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50)),
                ('contenido', models.TextField(max_length=50)),
                ('contexto', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(choices=[('admin', 'Administrador'), ('decano', 'Decano'), ('director', 'Director'), ('profesor', 'Profesor')], max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(max_length=50)),
                ('escuela', models.CharField(max_length=40)),
                ('numero_semestres', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('numero_creditos_graduacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('director', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=50)),
                ('contenido', models.TextField(max_length=50)),
                ('contexto', models.TextField(max_length=50)),
                ('proposito', models.TextField(max_length=50)),
                ('competencia', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='appprincipal.Competencia')),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisito',
            fields=[
                ('cursoP', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appprincipal.Curso', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='resultado',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='appprincipal.Resultado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appprincipal.Programa'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='curso',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='appprincipal.Curso'),
        ),
        migrations.AddField(
            model_name='actividadf',
            name='resultado',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='appprincipal.Resultado'),
        ),
        migrations.AddField(
            model_name='actividadevaluacion',
            name='indicador',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='appprincipal.Indicador'),
        ),
        migrations.AddField(
            model_name='prerequisito',
            name='curso',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='curs', to='appprincipal.Curso'),
        ),
    ]
