# Generated by Django 2.0.4 on 2018-06-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0002_indicadorevaluacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicadorEvaluacion',
            new_name='ActividadEvaluacion',
        ),
    ]
