# Generated by Django 2.0.4 on 2018-05-25 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0002_competencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='tipo',
            new_name='descripcion',
        ),
    ]
