# Generated by Django 2.0.4 on 2018-05-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0003_auto_20180525_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(choices=[('distingue', 'Distingue'), ('analiza', 'Analiza')], max_length=50)),
                ('contenido', models.TextField(blank=True, max_length=50)),
                ('contexto', models.TextField(blank=True, max_length=50)),
                ('proposito', models.TextField(blank=True, max_length=50)),
            ],
        ),
    ]
