# Generated by Django 2.0.4 on 2018-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0003_auto_20180611_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadevaluacion',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='actividadf',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='contenido',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='contexto',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='habilidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.TextField(choices=[('admin', 'Administrador'), ('decano', 'Decano'), ('director', 'Director'), ('profesor', 'Profesor')], max_length=500),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='contenido',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='contexto',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='proposito',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='verbo',
            field=models.CharField(max_length=50),
        ),
    ]
