# Generated by Django 2.0.4 on 2018-05-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0004_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='competencia',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='appprincipal.Competencia'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='curso',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='appprincipal.Curso'),
        ),
    ]
