# Generated by Django 2.0.4 on 2018-05-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0007_actividaddeformacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActividadDeFormacion',
            new_name='ActividadF',
        ),
    ]
