# Generated by Django 2.0.4 on 2018-06-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0009_prerequisito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prerequisito',
            old_name='Previo',
            new_name='cursos',
        ),
    ]
