# Generated by Django 2.0.4 on 2018-06-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0010_auto_20180610_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisito',
            name='curso',
        ),
    ]
