# Generated by Django 2.0.4 on 2018-06-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprincipal', '0011_remove_prerequisito_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisito',
            name='cursos',
            field=models.ManyToManyField(to='appprincipal.Curso'),
        ),
    ]
